version: '3.1'

services:
  s_pdb:
    container_name: c_pdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=zormax
      - POSTGRES_DB=zormax_db
    volumes:
      - ./postgresql_data:/var/lib/postgresql/data/pgdata