version: '3.9'

services:
  s_jenkins:
    container_name: c_jenkins
    image: zormax/jenkinswithdocker
    build: .
    ports:
      - 8085:8080
    volumes:
      - ./jenkins_github_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
