version: '3.9'

services:
  s_portainer:
    container_name: c_portainer
    image: portainer/portainer-ce
    ports:
      - 9000:9000
      - 8081:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data